# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    .travis.yml                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: thou <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/03/17 11:10:45 by thou              #+#    #+#              #
#    Updated: 2017/04/08 18:18:09 by thou             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

language: c
script:
    - env -i make re
os:
    - osx
env:
    - ARCH=x86_64
compiler:
    - clang
